language: cpp

compiler:
    - gcc

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_devtools
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github ohdsi/BoostCompiledLibraries

before_script:
  - sudo apt-get install libboost-dev

script:
    - ./travis-tool.sh run_tests

after_failure:
    - ./travis-tool.sh dump_logs

notifications:
  recipients:
    - msuchard@gmail.com
  email:
    on_success: change
    on_failure: always
